@startuml SafeClass

title Object Detection App

autonumber
participant User
participant SafeClassView
participant SafeClassController
participant SafeClassModel
participant Camera

User -> SafeClassView: Open app
SafeClassView -> SafeClassController: Initialize camera
SafeClassController -> Camera: Get available cameras
Camera -> SafeClassController: Cameras
SafeClassController -> Camera: Initialize camera
Camera -> SafeClassController: Camera controller
SafeClassController -> SafeClassView: Camera preview
SafeClassView -> Camera: Start image stream
Camera -> SafeClassController: Camera image
SafeClassController -> SafeClassModel: Detect objects
SafeClassModel -> SafeClassController: Detected objects
SafeClassController -> SafeClassView: Display results

@enduml
